### ISSUE TITLE
SSL cert verification settings

### ISSUE THREAD

**Issue by BuddhaOhneHals** [bcb/jsonrpcclient#10]
Hi,

it would be great if it's possible to pass arguments to `requests` to modify the SSL verification as described here: http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification

Prepared requests can do this too: http://docs.python-requests.org/en/master/user/advanced/#prepared-requests

Thanks,
Timo

**Comment by bcb** [comment]
You're right. It should accept the `verify='/path/to/certfile'` when calling HTTPServer. I'll push this through tomorrow.

**Comment by bcb** [comment]
Pushed a change so you can modify the requests [session](http://docs.python-requests.org/en/master/api/#requests.Session) before sending:

```python
s = HTTPServer('https://github.com')
s.session.verify = '/path/to/certfile'
s.request('get')
```

**Comment by BuddhaOhneHals** [comment]
Looks good! Thanks a lot. Btw the new version is missing on pypi.

**Comment by bcb** [comment]
Helps if I upload the distribution files! It's there now, thanks for letting me know.
