### ISSUE TITLE
Add param to tell client if response is expected

### ISSUE THREAD

**Issue by FMCorz** [bcb/jsonrpcclient#107]
Pass the parameter `expects_response` to `send_message` to tell the client know whether a response is expected or not.

Discussion started in #106.

**Comment by bcb** [comment]
Even though it's true the server should not respond to a notification, in certain cases the server will respond - that being when the request is invalid JSON or invalid JSON-RPC. In these cases it's impossible for the server to know that the request was a notification or request, and will respond with a JSON-RPC error response.

So the client should be listening for a response regardless of sending a request or notification object.

**Comment by bcb** [comment]
Ok, this has been added to version 3.2.1. I haven't updated your socket client to use it, though.

**Comment by FMCorz** [comment]
Hmm, on second thoughts you may be right. While a notification means that the client probably doesn't care about the response, that doesn't mean that there isn't one. I was looking for an example of a protocol where this was the case, but couldn't find an example. Either way, it doesn't hurt to have the parameter as it indicates that the request was a notification. Thanks!
