### ISSUE TITLE
Breaking change in public API not reflected in version number

### ISSUE THREAD

**Issue by alieh-rymasheuski** [bcb/jsonrpcclient#113]
Renaming jsonrpcclient.request to jsonrpcclient.requests is breaking, but version number doesn't indicate it.

https://github.com/bcb/jsonrpcclient/commit/f806944e06aef45d87142e27c2c1ca0fa1de2ee8

Basically, an upgrade from 3.1.0 to 3.2.0 breaks all code that relies on `from jsonrpcclient import request`.

**Comment by sergio-bershadsky** [comment]
+1

**Comment by bcb** [comment]
Yes I apologise for this, the module had to be renamed in order put back the [convenience function](https://github.com/bcb/jsonrpcclient/blob/master/jsonrpcclient/__init__.py#L5), which we had in version 2.

I'm usually very strict in following semver, but in this case didn't want to make a version 4 so soon after version 3.
