### ISSUE TITLE
KeyError -> Method not found

### ISSUE THREAD

**Issue by HasmedFara** [bcb/jsonrpcclient#114]
Hey guys, 

When a KeyError exception is raised  this is the response {"code": -32601, "message": "Method not found"} which is confused and misleading.

**Comment by bcb** [comment]
Thanks for reporting, I agree this is an issue, do you mind creating it in [jsonrpcserver](https://github.com/bcb/jsonrpcserver/issues) since the problem is in there.

**Comment by HasmedFara** [comment]
Sure. Thank you
