### ISSUE TITLE
Upgrade Jsonschema dependency to 3.x

### ISSUE THREAD

**Issue by nanopony** [bcb/jsonrpcclient#120]
Hello!

The current dependencies include `jsonschema >2 <3`. Is causes one of popular python dependency managers `poerty` to break, as it relies on jsonschema 3.0 with Draft 7 support.

Is the version lock still a mandatory requirement? jsonschema has a stable 3.0 release

**Comment by bcb** [comment]
No it's not a mandatory requirement. That was just in case the new major version broke the API. Are you able to update the version and send a PR?

**Comment by nanopony** [comment]
Thank you for the prompt reply! Yeah, I'll prepare PR tonight!

**Comment by bcb** [comment]
Pushed to pypi in version 3.3.2
