### ISSUE TITLE
Unable to set timeout for HTTPClient.

### ISSUE THREAD

**Issue by peilun-conflux** [bcb/jsonrpcclient#129]
Sorry, I didn't find the proper way to set the timeout for `HTTPClient` and is currently hacking `requests` to achieve this.

Is it not supported yet or am I missing any feature?

**Comment by bcb** [comment]
You can't with `request` (or notify), but you can with `send`:

```python
client.send(Request("ping"), timeout=10)
```

**Comment by peilun-conflux** [comment]
I see, thanks!

**Comment by pfra17** [comment]
Hi @bcb 
I am also trying to set a timeout for this call: `response = request("http://" + ipEntry.get() + port, "temperature_test", x)
`. 
Now I tried: `response = client.send(request("http://" + ipEntry.get() + port, "temperature_test", x), timeout=10)` but I get the errormessage: NameError: name 'client' is not defined. Which module do I need to import to get this work? I am thankful for any hints and answers. Best regards, pfra17

**Comment by bcb** [comment]
@pfra17  you need a capital r `Request`, which is a class, not a function, shown in the docs https://jsonrpcclient.readthedocs.io/en/latest/api.html
