### ISSUE TITLE
Feature: JSON-RPC Request validation/parsing

### ISSUE THREAD

**Issue by taylorjdawson** [bcb/jsonrpcclient#148]
This library has a method that parses JSON-RPC responses. It would be nice to add the ability to parse/validate JSON-RPC requests.

**Comment by bcb** [comment]
You can do this with [jsonrpcserver](https://github.com/bcb/jsonrpcserver).

```python
from jsonrpcserver import deserialize, schema, validate

request = '{"jsonrpc": "2.0", "method": "ping", "id": 1}'
validate(deserialize(request), schema)
```

Raises jsonschema.ValidationError if invalid.

**Comment by taylorjdawson** [comment]
Great thanks!
