### ISSUE TITLE
Cannot send "data" with error

### ISSUE THREAD

**Issue by MasterGroosha** [bcb/jsonrpcclient#153]
Hello, here's a sample code:
```python
@method
async def test(first, another):
    if first != "aaa":
        raise ApiError("My message", data="This is data")
    return "OK"
```

Unfortunately, "data" field is missing when client gets reply with error:
`{"jsonrpc": "2.0", "error": {"code": 1, "message": "My message"}, "id": 1}`

Python 3.7, using jsonrpcserver==4.1.3, aiohttp==3.6.2

**Comment by MasterGroosha** [comment]
Oops, my bad. I've mistaken the repo!
And enabling `debug=True` solved my problem (though it sounds strange)

**Comment by bcb** [comment]
@MasterGroosha there’s an issue here discussing this param https://github.com/bcb/jsonrpcserver/issues/110
