### ISSUE TITLE
Issue with jsonrpcclient and PyInstaller

### ISSUE THREAD

**Issue by pfra17** [bcb/jsonrpcclient#155]
Hi there,
I tried to use PyInstaller to compile my code. But when I want to launch the .exe file it tells me in the console:
`FileNotFoundError:[ Errno 2] No such file or directory: 'C:\\Users\\pfra\\AppData\\Local\\Temp\\_MEI55762\\jsonrpcclient\\response-schema.json'
[11988] Failed to execute script Q-Center`
I checked and the folder _MEI55762 is not present. I am importing:
`from jsonrpcclient import *
from jsonrpcclient.clients.http_client import HTTPClient
from jsonrpcclient.requests import Request
`

Do you know about this issue and do you think this has something to do with your package?
If you need my code let me know. Just didn't want to jung this issue with tons of code. 
Any help is highly appreciated.

**Comment by bcb** [comment]
response-schema.json is a file that jsonrpcclient uses to validate the response, it’s included in the repo here:
https://github.com/bcb/jsonrpcclient/blob/master/jsonrpcclient/response-schema.json

I’m not familiar with PyInstaller but it looks like you can include the file using a command line option:
https://pyinstaller.readthedocs.io/en/stable/spec-files.html#adding-data-files

**Comment by pfra17** [comment]
Thanks a lot @bcb . It worked to include the file.
