### ISSUE TITLE
Move deprecation warnings into server class constructors

### ISSUE THREAD

**Issue by bcb** [bcb/jsonrpcclient#30]
Rather than at import time.

Original comment by @saaj, [here](https://github.com/bcb/jsonrpcclient/commit/6196d5fa5f10cfbfcf093021e74742c80d9d171e#commitcomment-19076674).

**Comment by bcb** [comment]
After making this change I didn't commit it. Can't really see why this is a better choice than import time. The module itself is deprecated, not just the class.

**Comment by saaj** [comment]
Conceptually I agree that the module is deprecated. But, well, there's real-word circumstance of `warnings`' default filters and `unittest`'s runtime override. 

There's however another issue for you called `unittest` of Python 2 which doesn't re-enable warnings. So you may want to override `warnings` and/or `unittest` behaviour to normalise things. This may make you able to have module-level warnings.

I just updated (unintentionally, see semver issue ;-)) to 2.2.4 and have gotten no warning while running tests for the project I am working on.

**Comment by bcb** [comment]
There were no tests on the server modules, so they weren't being imported and therefore no warnings were triggered. I'll add tests for them.

**Comment by saaj** [comment]
I mean I ran tests for my code, which uses `jsonrpcclient`. In one module under test, for instance, there is `from jsonrpcclient.tornado_server import TornadoServer`. But there were no warnings.

**Comment by bcb** [comment]
You need to use `python -Wd` to see deprecation warnings.

**Comment by saaj** [comment]
In Python3-only codebase (which is the project I mentioned) one don't need to. ``unittest`` should re-enable wanrings.

**Comment by bcb** [comment]
Using `python -Wd -m unitest discover`, with python 3.5, I see warnings in tests from my own and other modules. I don't see any warnings in tests without `-Wd`.
