### ISSUE TITLE
Proposal: Add a Response class

### ISSUE THREAD

**Issue by bcb** [bcb/jsonrpcclient#42]
Currently the `request`-like methods return a primitive, normally the "result" part of the JSON-RPC response, such as "pong".

Instead, return an object of type `Response`. Some reasons to do this:
- Can hold more information about the response
- It's easier and more familiar for client classes to `return Response()`, rather than `return self.process_response()`. 

Down side would be, the user would have to use an attribute of the response (`response.result` or something) rather than just the raw return value. Edit: unless we override `__new__` to set the object's value. Otherwise, **Breaking change**

**Comment by jerry-sl** [comment]
+1 for this proposal.

**Comment by bcb** [comment]
I'm not 100% convinced this is worthwhile.

What extra information would be included in a Response object? Maybe the raw response, a string. Maybe an http_status, but since it's success response, it will almost always be 200. The most useful would be the request id.

**Comment by bcb** [comment]
Deciding against this.

**Comment by bcb** [comment]
Reconsidering this for version 3.
