### ISSUE TITLE
Disable logging requests and responses in config

### ISSUE THREAD

**Issue by bcb** [bcb/jsonrpcclient#45]
Add a config option to disable these

It can be preferable to turn the log entries off, particularly for large batch requests

**Comment by francislavoie** [comment]
I'm still looking for a way to disable logging, any way to do it?

**Comment by bcb** [comment]
You can like this:
```python
import logging
logging.getLogger("jsonrpcclient.client.request").setLevel(logging.WARNING)
logging.getLogger("jsonrpcclient.client.response").setLevel(logging.WARNING)
```
