### ISSUE TITLE
notify() method shouldn’t wait for a response

### ISSUE THREAD

**Issue by johnkit** [bcb/jsonrpcclient#50]
It looks like the client notify() methods wait for a response from the server, however, the [jsonrpc standard](http://www.jsonrpc.org/specification#notification) states that “The Server MUST NOT reply to a Notification”. Is this a bug in the client software?

**Comment by bcb** [comment]
notify() should not wait for a response.

Can you give an example?

**Comment by bcb** [comment]
Well, the spec doesn't say notify shouldn't wait for a response. It only says servers shouldn't reply.

**Comment by johnkit** [comment]
I really can't give an example because the jsonrpcserver examples respond to notification messages. Maybe I should create an issue in *that* repo that the examples shouldn't do that.
