### ISSUE TITLE
Make Project's Source more visible

### ISSUE THREAD

**Issue by sbrandtb** [bcb/jsonrpcclient#53]
Hey, nice project and actually the best JSON RPC client I've found so far, regarding the amount of provided clients and the interface.

However, it was hard for me to find the project's source on the internet. In fact, I was close to thinking it is not hosted anywhere until I found the link to `jsonrpcserver` in the readme.

AFAIK, usually the link to the Github source page is used in the `url` field in `setup.py` and also mentioned in the docs somewhere. Would probably be great for the project to make it more visible :)

**Comment by bcb** [comment]
You're right, it should be in `setup.py`. Will add it.

**Comment by bcb** [comment]
There is a link in the [docs](https://jsonrpcclient.readthedocs.io/en/latest/), (although it's not very clear):

![screen shot 2017-08-06 at 08 57 18](https://user-images.githubusercontent.com/134581/28999317-54c26cac-7a85-11e7-8d13-ced12b3e3542.png)
