### ISSUE TITLE
documentation: pip install 

### ISSUE THREAD

**Issue by 42sol-eu** [bcb/jsonrpcclient#68]
on my windows 10 account a pip install has to be done without the single quotes

`pip install jsonrpcclient[requests]` works fine.

I do use pip version 10.0.1. 
Is this only for windows or 
If you like I may update the docs and create a pull request.

Thanks for the great work.
  Felix

**Comment by bcb** [comment]
On my shell, (zsh in mac os), it gives me an error when I omit the quotes:
```sh
$ pip install jsonrpcclient[requests]
zsh: no matches found: jsonrpcclient[requests]
```

Using double quotes does work though (pip install "jsonrpcclient[requests]").

If that works for you it might be the best option.

**Comment by 42sol-eu** [comment]
you are right. Double quotes work.

I did an additional test the single quotes work on 
- Windows PowerShell 
- Windows Bash (e.g. git bash)

But only double quites not on cmd.exe based shells.

the double quotes would be the best choice.

**Comment by bcb** [comment]
Ok I'll make this change in the docs
