### ISSUE TITLE
jsonrpcclient cannot be used with Python 2 anymore

### ISSUE THREAD

**Issue by alorence** [bcb/jsonrpcclient#80]
Hello,

Yesterday, file __init__.py was modified by commit 4e2e0c0430e0b:

```
def notify(
    endpoint,
    method,
    *args,
    trim_log_values=False,
    validate_against_schema=True,
    **kwargs
):
    # [...]

def request(
    endpoint,
    method,
    *args,
    id_generator=None,
    trim_log_values=False,
    validate_against_schema=True,
    **kwargs
):
    # [...]
```

Unfortunately, specifying parameters after `*args` is not supported in python 2. This caused:
> SyntaxError: invalid syntax

As a result, the library cannot be used anymore in Python 2 projects, but this was not mentioned in CHANGELOG.

**Comment by bcb** [comment]
You're right.

I don't think we can support these new params in Python 2. 

Will have to remove this version (2.6.1) and start a new 3.x release.

**Comment by bcb** [comment]
Have removed 2.6.1 from pypi.

Will create a 3.x release tonight.

**Comment by bcb** [comment]
fyi @ferrouswheel

**Comment by bcb** [comment]
Planning to release 3.0 tonight, only #85 is left to do. Also need to decide which minimum python 3 version to support.

**Comment by alorence** [comment]
Python 3.4 is probably a reasonable minimum

**Comment by bcb** [comment]
I'm thinking 3.5, because four of the six clients are asyncio ones. Python < 3.5 users can use the jsonrpcclient 2.x releases.

**Comment by bcb** [comment]
Have pushed a 3.0 release candidate to pypi (see #86)

Thanks for reporting this @alorence .
