### ISSUE TITLE
Parse Output

### ISSUE THREAD

**Issue by uiucgrad** [bcb/jsonrpcclient#90]
Thanks for a great client.  Everything seems to be working correctly but i'm not sure how to parse the output into JSON so I can read particular values in the result.  I can see the 
--> {"
<-- {"
but can't figure out how to pass the <-- so it can be parse.  Is there a way to output just the return value?

**Comment by bcb** [comment]
Those are just log entries. The return value is the "result" part of the json-rpc response.

However in the new 3.0 version, I'm considering returning a Response object, with result and id attributes.
